### ISSUE TITLE
npm: package-lock.json missing

### ISSUE THREAD

**Issue by pawelkmpt** [saas786/cxl-blocks#1]
@saas786 this repository is missing `package-lock.json` file. Moreover, this file is `.gitignore`d.
What's behind such decision? Can we add it?

```
> npm ci --prefix=public/wp-content/plugins/cxl-blocks
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
```

**Comment by saas786** [comment]
> @saas786 this repository is missing `package-lock.json` file. Moreover, this file is `.gitignore`d.
> What's behind such decision? Can we add it?
> 
> ```
> > npm ci --prefix=public/wp-content/plugins/cxl-blocks
> npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
> ```

Committed already, released a version, and also attached ready to use files as zip, please test it out. (CXL Blocks & CXL Common Lib)
